services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./panel_control_app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: "redis:6-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
